services:
  jump-into-job-frontend:
    build:
      context: .
    ports:
      - '3001:3000'
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - bin/
            - .github/
            - .git/
        - action: rebuild
          path: package.json
    environment:
      - NODE_ENV=development 
      - BROWSERSLIST_DISABLE_CACHE=false
    restart: unless-stopped
