name: Windows Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install dependencies (Optional)
        run: |
          git pull origin main
          docker compose down
          docker compose up --build -d
          docker compose exec backend composer install
          docker compose exec backend php artisan optimize:clear
          docker compose exec backend php artisan migrate:fresh --seed --force